/*
 * layer_table.c - Configuration of the 28 CNN layers.
 *
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY.
 * Any changes made here will be lost during the next generator run.
 *
 * Generator: runtime_bare_metal/scripts/generate_layer_table.py
 * Model:     model_MobileNetV2_HSV_256x256.keras
 *
 * To change a value, correct the generator and run it again.
 *
 *     Author: Angel Obando
 *
 */

#include "layer_table.h"

const struct layer_config_t layer_table[ NUM_LAYERS ] = {
    /* [ 0] conv1 */
    {
        .common_mode          = 0,
        .common_cin           = 3,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = true,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 27,
        .cnn_max_co           = 1,
        .cnn_max_x            = 63,
        .cnn_max_y            = 3,
        .cnn_max_tile_x       = 1,
        .cnn_max_tile_y       = 31,
        .cnn_shift            = 7,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 46271,
        .dma_cout             = 32,
        .dma_img_w            = 256,
        .dma_img_h            = 256,
        .dma_tile_w           = 128,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 2,
        .dma_num_tile_y       = 32,
        .dma_weight_words     = 54,
        .dma_bias_words       = 8,
        .dma_addr_w           = 0x01000000,
        .dma_addr_in          = 0x02000000,
        .dma_addr_out         = 0x02100000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010000,
    },
    /* [ 1] irb1_dw */
    {
        .common_mode          = 1,
        .common_cin           = 32,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 9,
        .cnn_max_co           = 1,
        .cnn_max_x            = 127,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 15,
        .cnn_shift            = 5,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 55176,
        .dma_cout             = 32,
        .dma_img_w            = 128,
        .dma_img_h            = 128,
        .dma_tile_w           = 128,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 16,
        .dma_weight_words     = 18,
        .dma_bias_words       = 8,
        .dma_addr_w           = 0x01000360,
        .dma_addr_in          = 0x02100000,
        .dma_addr_out         = 0x02180000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010080,
    },
    /* [ 2] irb1_pw */
    {
        .common_mode          = 2,
        .common_cin           = 32,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = false,
        .common_pool_type     = false,
        .cnn_max_inner        = 32,
        .cnn_max_co           = 0,
        .cnn_max_x            = 127,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 15,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 0,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 54990,
        .dma_cout             = 16,
        .dma_img_w            = 128,
        .dma_img_h            = 128,
        .dma_tile_w           = 128,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 16,
        .dma_weight_words     = 32,
        .dma_bias_words       = 4,
        .dma_addr_w           = 0x01000480,
        .dma_addr_in          = 0x02180000,
        .dma_addr_out         = 0x02200000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010100,
    },
    /* [ 3] irb2_exp */
    {
        .common_mode          = 2,
        .common_cin           = 16,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 16,
        .cnn_max_co           = 1,
        .cnn_max_x            = 127,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 15,
        .cnn_shift            = 6,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 42050,
        .dma_cout             = 32,
        .dma_img_w            = 128,
        .dma_img_h            = 128,
        .dma_tile_w           = 128,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 16,
        .dma_weight_words     = 32,
        .dma_bias_words       = 8,
        .dma_addr_w           = 0x01000680,
        .dma_addr_in          = 0x02200000,
        .dma_addr_out         = 0x02240000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010140,
    },
    /* [ 4] irb2_dw */
    {
        .common_mode          = 1,
        .common_cin           = 32,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = true,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 9,
        .cnn_max_co           = 1,
        .cnn_max_x            = 63,
        .cnn_max_y            = 3,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 15,
        .cnn_shift            = 5,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 44263,
        .dma_cout             = 32,
        .dma_img_w            = 128,
        .dma_img_h            = 128,
        .dma_tile_w           = 128,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 16,
        .dma_weight_words     = 18,
        .dma_bias_words       = 8,
        .dma_addr_w           = 0x01000880,
        .dma_addr_in          = 0x02240000,
        .dma_addr_out         = 0x022C0000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x010101C0,
    },
    /* [ 5] irb2_pw */
    {
        .common_mode          = 2,
        .common_cin           = 32,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = false,
        .common_pool_type     = false,
        .cnn_max_inner        = 32,
        .cnn_max_co           = 1,
        .cnn_max_x            = 63,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 7,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 0,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 51825,
        .dma_cout             = 24,
        .dma_img_w            = 64,
        .dma_img_h            = 64,
        .dma_tile_w           = 64,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 8,
        .dma_weight_words     = 64,
        .dma_bias_words       = 8,
        .dma_addr_w           = 0x010009A0,
        .dma_addr_in          = 0x022C0000,
        .dma_addr_out         = 0x022E0000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010240,
    },
    /* [ 6] irb3_exp */
    {
        .common_mode          = 2,
        .common_cin           = 24,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 24,
        .cnn_max_co           = 2,
        .cnn_max_x            = 63,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 7,
        .cnn_shift            = 6,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 36048,
        .dma_cout             = 48,
        .dma_img_w            = 64,
        .dma_img_h            = 64,
        .dma_tile_w           = 64,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 8,
        .dma_weight_words     = 72,
        .dma_bias_words       = 12,
        .dma_addr_w           = 0x01000DA0,
        .dma_addr_in          = 0x022E0000,
        .dma_addr_out         = 0x02300000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x010102C0,
    },
    /* [ 7] irb3_dw */
    {
        .common_mode          = 1,
        .common_cin           = 48,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 9,
        .cnn_max_co           = 2,
        .cnn_max_x            = 63,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 7,
        .cnn_shift            = 5,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 35361,
        .dma_cout             = 48,
        .dma_img_w            = 64,
        .dma_img_h            = 64,
        .dma_tile_w           = 64,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 8,
        .dma_weight_words     = 27,
        .dma_bias_words       = 12,
        .dma_addr_w           = 0x01001220,
        .dma_addr_in          = 0x02300000,
        .dma_addr_out         = 0x02330000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010380,
    },
    /* [ 8] irb3_pw */
    {
        .common_mode          = 2,
        .common_cin           = 48,
        .common_has_residual  = true,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = false,
        .common_pool_type     = false,
        .cnn_max_inner        = 48,
        .cnn_max_co           = 1,
        .cnn_max_x            = 63,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 7,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 0,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 42686,
        .dma_cout             = 24,
        .dma_img_w            = 64,
        .dma_img_h            = 64,
        .dma_tile_w           = 64,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 8,
        .dma_weight_words     = 96,
        .dma_bias_words       = 8,
        .dma_addr_w           = 0x010013D0,
        .dma_addr_in          = 0x02330000,
        .dma_addr_out         = 0x02360000,
        .dma_addr_res         = 0x022E0000,
        .dma_addr_bias        = 0x01010440,
    },
    /* [ 9] irb4_exp */
    {
        .common_mode          = 2,
        .common_cin           = 24,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 24,
        .cnn_max_co           = 2,
        .cnn_max_x            = 63,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 7,
        .cnn_shift            = 7,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 42025,
        .dma_cout             = 48,
        .dma_img_w            = 64,
        .dma_img_h            = 64,
        .dma_tile_w           = 64,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 8,
        .dma_weight_words     = 72,
        .dma_bias_words       = 12,
        .dma_addr_w           = 0x010019D0,
        .dma_addr_in          = 0x02360000,
        .dma_addr_out         = 0x02380000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x010104C0,
    },
    /* [10] irb4_dw */
    {
        .common_mode          = 1,
        .common_cin           = 48,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = true,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 9,
        .cnn_max_co           = 2,
        .cnn_max_x            = 31,
        .cnn_max_y            = 3,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 7,
        .cnn_shift            = 6,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 61388,
        .dma_cout             = 48,
        .dma_img_w            = 64,
        .dma_img_h            = 64,
        .dma_tile_w           = 64,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 8,
        .dma_weight_words     = 27,
        .dma_bias_words       = 12,
        .dma_addr_w           = 0x01001E50,
        .dma_addr_in          = 0x02380000,
        .dma_addr_out         = 0x023B0000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010580,
    },
    /* [11] irb4_pw */
    {
        .common_mode          = 2,
        .common_cin           = 48,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = false,
        .common_pool_type     = false,
        .cnn_max_inner        = 48,
        .cnn_max_co           = 1,
        .cnn_max_x            = 31,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 3,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 0,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 51770,
        .dma_cout             = 32,
        .dma_img_w            = 32,
        .dma_img_h            = 32,
        .dma_tile_w           = 32,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 4,
        .dma_weight_words     = 96,
        .dma_bias_words       = 8,
        .dma_addr_w           = 0x01002000,
        .dma_addr_in          = 0x023B0000,
        .dma_addr_out         = 0x023BC000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010640,
    },
    /* [12] irb5_exp */
    {
        .common_mode          = 2,
        .common_cin           = 32,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 32,
        .cnn_max_co           = 3,
        .cnn_max_x            = 31,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 3,
        .cnn_shift            = 7,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 50853,
        .dma_cout             = 64,
        .dma_img_w            = 32,
        .dma_img_h            = 32,
        .dma_tile_w           = 32,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 4,
        .dma_weight_words     = 128,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x01002600,
        .dma_addr_in          = 0x023BC000,
        .dma_addr_out         = 0x023C4000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x010106C0,
    },
    /* [13] irb5_dw */
    {
        .common_mode          = 1,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 9,
        .cnn_max_co           = 3,
        .cnn_max_x            = 31,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 3,
        .cnn_shift            = 6,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 55149,
        .dma_cout             = 64,
        .dma_img_w            = 32,
        .dma_img_h            = 32,
        .dma_tile_w           = 32,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 4,
        .dma_weight_words     = 36,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x01002E00,
        .dma_addr_in          = 0x023C4000,
        .dma_addr_out         = 0x023D4000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x010107C0,
    },
    /* [14] irb5_pw */
    {
        .common_mode          = 2,
        .common_cin           = 64,
        .common_has_residual  = true,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = false,
        .common_pool_type     = false,
        .cnn_max_inner        = 64,
        .cnn_max_co           = 1,
        .cnn_max_x            = 31,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 3,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 0,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 56721,
        .dma_cout             = 32,
        .dma_img_w            = 32,
        .dma_img_h            = 32,
        .dma_tile_w           = 32,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 4,
        .dma_weight_words     = 128,
        .dma_bias_words       = 8,
        .dma_addr_w           = 0x01003040,
        .dma_addr_in          = 0x023D4000,
        .dma_addr_out         = 0x023E4000,
        .dma_addr_res         = 0x023BC000,
        .dma_addr_bias        = 0x010108C0,
    },
    /* [15] irb6_exp */
    {
        .common_mode          = 2,
        .common_cin           = 32,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 32,
        .cnn_max_co           = 3,
        .cnn_max_x            = 31,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 3,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 65059,
        .dma_cout             = 64,
        .dma_img_w            = 32,
        .dma_img_h            = 32,
        .dma_tile_w           = 32,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 4,
        .dma_weight_words     = 128,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x01003840,
        .dma_addr_in          = 0x023E4000,
        .dma_addr_out         = 0x023EC000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010940,
    },
    /* [16] irb6_dw */
    {
        .common_mode          = 1,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = true,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 9,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 3,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 3,
        .cnn_shift            = 5,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 33277,
        .dma_cout             = 64,
        .dma_img_w            = 32,
        .dma_img_h            = 32,
        .dma_tile_w           = 32,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 4,
        .dma_weight_words     = 36,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x01004040,
        .dma_addr_in          = 0x023EC000,
        .dma_addr_out         = 0x023FC000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010A40,
    },
    /* [17] irb6_pw */
    {
        .common_mode          = 2,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = false,
        .common_pool_type     = false,
        .cnn_max_inner        = 64,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 0,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 48462,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 256,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x01004280,
        .dma_addr_in          = 0x023FC000,
        .dma_addr_out         = 0x02400000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010B40,
    },
    /* [18] irb7_exp */
    {
        .common_mode          = 2,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 64,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 7,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 35015,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 256,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x01005280,
        .dma_addr_in          = 0x02400000,
        .dma_addr_out         = 0x02404000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010C40,
    },
    /* [19] irb7_dw */
    {
        .common_mode          = 1,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 9,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 5,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 47840,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 36,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x01006280,
        .dma_addr_in          = 0x02404000,
        .dma_addr_out         = 0x02408000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010D40,
    },
    /* [20] irb7_pw */
    {
        .common_mode          = 2,
        .common_cin           = 64,
        .common_has_residual  = true,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = false,
        .common_pool_type     = false,
        .cnn_max_inner        = 64,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 0,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 60124,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 256,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x010064C0,
        .dma_addr_in          = 0x02408000,
        .dma_addr_out         = 0x0240C000,
        .dma_addr_res         = 0x02400000,
        .dma_addr_bias        = 0x01010E40,
    },
    /* [21] irb8_exp */
    {
        .common_mode          = 2,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 64,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 49553,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 256,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x010074C0,
        .dma_addr_in          = 0x0240C000,
        .dma_addr_out         = 0x02410000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01010F40,
    },
    /* [22] irb8_dw */
    {
        .common_mode          = 1,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 9,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 6,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 44677,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 36,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x010084C0,
        .dma_addr_in          = 0x02410000,
        .dma_addr_out         = 0x02414000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01011040,
    },
    /* [23] irb8_pw */
    {
        .common_mode          = 2,
        .common_cin           = 64,
        .common_has_residual  = true,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = false,
        .common_pool_type     = false,
        .cnn_max_inner        = 64,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 7,
        .cnn_relu6_val        = 0,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 35763,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 256,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x01008700,
        .dma_addr_in          = 0x02414000,
        .dma_addr_out         = 0x02418000,
        .dma_addr_res         = 0x0240C000,
        .dma_addr_bias        = 0x01011140,
    },
    /* [24] irb9_exp */
    {
        .common_mode          = 2,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 64,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 41658,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 256,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x01009700,
        .dma_addr_in          = 0x02418000,
        .dma_addr_out         = 0x0241C000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01011240,
    },
    /* [25] irb9_dw */
    {
        .common_mode          = 1,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = false,
        .cnn_max_inner        = 9,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 6,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 64622,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 36,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x0100A700,
        .dma_addr_in          = 0x0241C000,
        .dma_addr_out         = 0x02420000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01011340,
    },
    /* [26] irb9_pw */
    {
        .common_mode          = 2,
        .common_cin           = 64,
        .common_has_residual  = true,
        .common_pool_en       = false,
        .common_stride_en     = false,
        .common_relu_en       = false,
        .common_pool_type     = false,
        .cnn_max_inner        = 64,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 7,
        .cnn_relu6_val        = 0,
        .cnn_gap_shift        = 0,
        .cnn_mult             = 42229,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 256,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x0100A940,
        .dma_addr_in          = 0x02420000,
        .dma_addr_out         = 0x02424000,
        .dma_addr_res         = 0x02418000,
        .dma_addr_bias        = 0x01011440,
    },
    /* [27] conv_last */
    {
        .common_mode          = 2,
        .common_cin           = 64,
        .common_has_residual  = false,
        .common_pool_en       = true,
        .common_stride_en     = false,
        .common_relu_en       = true,
        .common_pool_type     = true,
        .cnn_max_inner        = 64,
        .cnn_max_co           = 3,
        .cnn_max_x            = 15,
        .cnn_max_y            = 7,
        .cnn_max_tile_x       = 0,
        .cnn_max_tile_y       = 1,
        .cnn_shift            = 8,
        .cnn_relu6_val        = 127,
        .cnn_gap_shift        = 7,
        .cnn_mult             = 36079,
        .dma_cout             = 64,
        .dma_img_w            = 16,
        .dma_img_h            = 16,
        .dma_tile_w           = 16,
        .dma_tile_h           = 8,
        .dma_num_tile_x       = 1,
        .dma_num_tile_y       = 2,
        .dma_weight_words     = 256,
        .dma_bias_words       = 16,
        .dma_addr_w           = 0x0100B940,
        .dma_addr_in          = 0x02424000,
        .dma_addr_out         = 0x02428000,
        .dma_addr_res         = 0x00000000,
        .dma_addr_bias        = 0x01011540,
    },
};
